version: "3.8"

services:
  yp:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/arm64"
    image: pimagroupregistery.azurecr.io/api:1.0.0
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8055/server/health"]
      interval: 30s
      timeout: 10s
      retries: 3