type: object
properties:
  version:
    type: integer
    example: 1
  yourpartner:
    type: string
  vendor:
    type: string
  collections:
    type: array
    items:
      $ref: '../openapi.yaml#/components/schemas/Collections'
  fields:
    type: array
    items:
      $ref: '../openapi.yaml#/components/schemas/Fields'
  relations:
    type: array
    items:
      $ref: '../openapi.yaml#/components/schemas/Relations'
