table: yp_settings

columns:
  id:
    increments: true
    primary: true
    nullable: false
  project_name:
    type: string
    length: 100
    nullable: false
    default: 'YourPartner'
  project_url:
    type: string
    length: 255
  project_color:
    type: string
    length: 10
    default: '#004edb'
  project_logo:
    type: uuid
    references:
      table: yp_files
      column: id
  public_favicon:
    type: uuid
    references:
      table: yp_files
      column: id
  auth_login_attempts:
    type: integer
    default: 25
    unsigned: true
  auth_password_policy:
    type: string
    length: 100
  public_registration:
    type: boolean
    default: false
  public_registration_verify_email:
    type: boolean
    default: true
  public_registration_role:
    type: uuid
    references:
      table: yp_roles
      column: id
  public_registration_email_filter:
    type: json
  storage_asset_transform:
    type: string # One of: 'all', 'none', 'presets'
    length: 7
    default: all
  storage_asset_presets:
    type: json
  storage_default_folder:
    type: uuid
    references:
      table: yp_folders
      column: id
  default_language:
    type: string
    length: 10
    default: 'en-US'
  project_from_email:
    type: string
    length: 255
    default: 'noreply@yourpartner.com'
  organization_id:
    type: uuid
    nullable: true
    references:
      table: yp_organizations
      column: id
  